import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { PrismicRichText } from '@prismicio/react';
import { createPrismicClient } from '../prismic-config';

export async function getStaticProps(context) {
  const client = createPrismicClient({ context });

  const home = await client.getByUID('page', 'home');

  return {
    props: {
      home,
    },
  };
}

export default function Home({ home }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <PrismicRichText field={home.data.header} />
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
